In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [12]:
df = pd.read_csv('../cardio_original.csv', sep = ";")
print(df.shape)
df.head()

(70000, 13)

   id    age  gender  height  weight  ...  gluc  smoke  alco  active  cardio
0   0  18393       2     168    62.0  ...     1      0     0       1       0
1   1  20228       1     156    85.0  ...     1      0     0       1       1
2   2  18857       1     165    64.0  ...     1      0     0       0       1
3   3  17623       2     169    82.0  ...     1      0     0       1       1
4   4  17474       1     156    56.0  ...     1      0     0       0       0

[5 rows x 13 columns]

In [13]:
# Remove "id" column
df = df.drop(columns=['id'])
# Move class column to the beginning
class_col = df.pop('cardio')
df.insert(0, 'cardio', class_col)
df.head()

   cardio    age  gender  height  ...  gluc  smoke  alco  active
0       0  18393       2     168  ...     1      0     0       1
1       1  20228       1     156  ...     1      0     0       1
2       1  18857       1     165  ...     1      0     0       0
3       1  17623       2     169  ...     1      0     0       1
4       0  17474       1     156  ...     1      0     0       0

[5 rows x 12 columns]

In [14]:
# Check type and values of each column
for c in df.columns:
    print("Column:", c)
    print("Type:", df[c].dtype)
    print("Number of unique values:", df[c].nunique())

Column: cardio
Type: int64
Number of unique values: 2
Column: age
Type: int64
Number of unique values: 8076
Column: gender
Type: int64
Number of unique values: 2
Column: height
Type: int64
Number of unique values: 109
Column: weight
Type: float64
Number of unique values: 287
Column: ap_hi
Type: int64
Number of unique values: 153
Column: ap_lo
Type: int64
Number of unique values: 157
Column: cholesterol
Type: int64
Number of unique values: 3
Column: gluc
Type: int64
Number of unique values: 3
Column: smoke
Type: int64
Number of unique values: 2
Column: alco
Type: int64
Number of unique values: 2
Column: active
Type: int64
Number of unique values: 2

In [15]:
df.cardio.value_counts()

cardio
0    35021
1    34979
Name: count, dtype: int64

In [16]:
# Remove "age", "height", "weight", "ap_hi", and "ap_lo" columns
df = df.drop(columns=['age', 'height', 'weight', 'ap_hi', 'ap_lo'])
# Cast columns to str type for subgroup library
for c in df.columns:
    df[c] = df[c].astype(str)
# Save the processed DataFrame
df.to_csv("../cardio.csv", index=False)

In [17]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["cardio"])
df_tuning, df_val = train_test_split(df_train, test_size=0.2, random_state=42, stratify=df_train["cardio"])
df_train.to_csv("../cardio_train.csv", index=False)
df_test.to_csv("../cardio_test.csv", index=False)
df_tuning.to_csv("../cardio_tuning.csv", index=False)
df_val.to_csv("../cardio_validation.csv", index=False)

In [18]:
df.shape

(70000, 7)