In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [19]:
df = pd.read_csv("../depression_original.csv")
print(df.shape)
df.head()

(502, 11)

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,28,2.0,4.0,7-8 hours,Moderate,Yes,9,2,Yes,No
1,Male,28,4.0,5.0,5-6 hours,Healthy,Yes,7,1,Yes,No
2,Male,25,1.0,3.0,5-6 hours,Unhealthy,Yes,10,4,No,Yes
3,Male,23,1.0,4.0,More than 8 hours,Unhealthy,Yes,7,2,Yes,No
4,Female,31,1.0,5.0,More than 8 hours,Healthy,Yes,4,2,Yes,No

In [20]:
# Move class column to the beginning
class_col = df.pop('Depression')
df.insert(0, 'Depression', class_col)
df.head()

,Depression,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness
0,No,Male,28,2.0,4.0,7-8 hours,Moderate,Yes,9,2,Yes
1,No,Male,28,4.0,5.0,5-6 hours,Healthy,Yes,7,1,Yes
2,Yes,Male,25,1.0,3.0,5-6 hours,Unhealthy,Yes,10,4,No
3,No,Male,23,1.0,4.0,More than 8 hours,Unhealthy,Yes,7,2,Yes
4,No,Female,31,1.0,5.0,More than 8 hours,Healthy,Yes,4,2,Yes

In [21]:
# Check type and values of each column
for c in df.columns:
    print("Column:", c)
    print("Type:", df[c].dtype)
    print("Number of unique values:", df[c].nunique())

Column: Depression
Type: object
Number of unique values: 2
Column: Gender
Type: object
Number of unique values: 2
Column: Age
Type: int64
Number of unique values: 17
Column: Academic Pressure
Type: float64
Number of unique values: 5
Column: Study Satisfaction
Type: float64
Number of unique values: 5
Column: Sleep Duration
Type: object
Number of unique values: 4
Column: Dietary Habits
Type: object
Number of unique values: 3
Column: Have you ever had suicidal thoughts ?
Type: object
Number of unique values: 2
Column: Study Hours
Type: int64
Number of unique values: 13
Column: Financial Stress
Type: int64
Number of unique values: 5
Column: Family History of Mental Illness
Type: object
Number of unique values: 2

In [22]:
df.Depression.value_counts()

Depression
Yes    252
No     250
Name: count, dtype: int64

In [23]:
#Remove white spaces and '?' from column names
df.columns = df.columns.str.replace('?', '', regex=False)
df.columns = df.columns.str.replace(' ', '_', regex=False)
df.columns

Index(['Depression', 'Gender', 'Age', 'Academic_Pressure',
       'Study_Satisfaction', 'Sleep_Duration', 'Dietary_Habits',
       'Have_you_ever_had_suicidal_thoughts_', 'Study_Hours',
       'Financial_Stress', 'Family_History_of_Mental_Illness'],
      dtype='object')

In [ ]:
# Remove 'Age' and 'Study_Hours' columns
df = df.drop(columns=['Age', 'Study_Hours'])
# Cast columns to str type for subgroup library
for c in df.columns:
    df[c] = df[c].astype(str)
# Save the processed DataFrame
df.to_csv("../depression.csv", index=False)

In [25]:
df_train, df_test = train_test_split(df, test_size=0.2, stratify=df["Depression"], random_state=42)
df_tuning, df_validation = train_test_split(df_train, test_size=0.2, stratify=df_train["Depression"], random_state=42)
df_train.to_csv("../depression_train.csv", index=False)
df_test.to_csv("../depression_test.csv", index=False)
df_tuning.to_csv("../depression_tuning.csv", index=False)
df_validation.to_csv("../depression_validation.csv", index=False)

In [26]:
df.shape

(502, 9)