In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('selected_parameters.csv', sep='\t')
df.head()

    Dataset        Model Quality measure / OR & PPV
0  Mushroom          BSD                  Piatetsky
1  Mushroom       SDMap*                      WRAcc
2  Mushroom  BerryFinder                    Inf/0.5
3     Chess          BSD                      WRAcc
4     Chess       SDMap*                          -

In [20]:
# df.groupby(["Dataset", "Model"]).agg({"Quality measure / OR & PPV": "first"})
# display(df.pivot(index="Model", columns="Dataset", values="Quality measure / OR & PPV"))
piv = df.pivot(index="Dataset", columns="Model", values="Quality measure / OR & PPV")[["BerryFinder", "BSD", "SDMap*"]]
index_order = ["Mushroom", "Chess", "Student", "Connect", "Healthy Aging", "Car", "Soybean", "Dermatology", "Depression", "Vancomycin", "MIMIC-IV", "Cardio"]
piv = piv.reindex(index_order)
display(piv)
print(piv.to_latex(float_format="%.2f", na_rep="--"))

Model         BerryFinder        BSD     SDMap*
Dataset
Mushroom          Inf/0.5  Piatetsky      WRAcc
Chess            1.8/0.99      WRAcc          -
Student           6.0/0.6      WRAcc          -
Connect           1.2/0.8    Biomial          -
Healthy Aging  1.2 / 0.50   Binomial  Piatetsky
Car            3.0 / 0.60   Binomial      WRAcc
Soybean        20.0 / 0.6      WRAcc          -
Dermatology    inf / 0.95  Piatetsky          -
Depression        6.0/0.6  Piatetsky      WRAcc
Vancomycin        1.2/0.8   Binomial  Piatetsky
MIMIC-IV         1.8/0.40   Binomial      WRAcc
Cardio          1.2 / 0.4   Binomial      WRAcc

\begin{tabular}{llll}
\toprule
Model & BerryFinder & BSD & SDMap* \\
Dataset &  &  &  \\
\midrule
Mushroom & Inf/0.5 & Piatetsky & WRAcc \\
Chess & 1.8/0.99 & WRAcc & - \\
Student & 6.0/0.6 & WRAcc & - \\
Connect & 1.2/0.8 & Biomial & - \\
Healthy Aging & 1.2 / 0.50 & Binomial & Piatetsky \\
Car & 3.0 / 0.60 & Binomial & WRAcc \\
Soybean & 20.0 / 0.6 & WRAcc & - \\
Dermatology & inf / 0.95 & Piatetsky & - \\
Depression & 6.0/0.6 & Piatetsky & WRAcc \\
Vancomycin & 1.2/0.8 & Binomial & Piatetsky \\
MIMIC-IV & 1.8/0.40 & Binomial & WRAcc \\
Cardio & 1.2 / 0.4 & Binomial & WRAcc \\
\bottomrule
\end{tabular}